### ISSUE TITLE
Not getting all the triangles in a hull.

### ISSUE THREAD

**Issue by shekarmantha** [akuukka/quickhull#1]
I am using this library and I think I found a problem. Not sure where to post this question so I am posting it here.

If I have a set of four points:

(-3.000000 -0.250000 -0.800000) (-3.000000 0.250000 -0.800000) (-3.125000 0.250000 -0.750000) (-3.125000 -0.250000 -0.750000)

I am able to create a hull but the hull only has two triangles:

`-3.000000 -0.250000 -0.800000 -3.437502 0.250000 -0.624999 -3.000000 0.250000 -0.800000 -3.437502 0.250000 -0.624999 -3.000000 -0.250000 -0.800000 -3.437502 -0.250000 -0.624999'

I would have thought there would be four triangles since the 4 input points above form a tetrahedron. Am I missing something?

**Comment by akuukka** [comment]
Thanks!  I will investigate this.

**Comment by shekarmantha** [comment]
Thank you. I really appreciate your work. If I can help, please tell me. I can code and test as well.

**Comment by akuukka** [comment]
The points you have given all lie on the same plane so the "tetrahedron" they form is infinitely thin.

**Comment by shekarmantha** [comment]
Yes, but is that what is preventing them from forming a tetrahedron? OK, I will look into why this is happening in my code. I am trying to compute a hull based no the intersection of a hexahedron and a tetrahedron and that data is coming from an external source. 

Thanks

**Comment by akuukka** [comment]
Well, if QuickHull is given a point cloud where all points lie on the same plane, it will return a set of triangles that covers all the points but doesn't form a triangle mesh with volume. 

Now that I think of it again, perhaps we should return an infinitely thin mesh in these degenerate cases... only a few lines of could would have to be changed.

**Comment by shekarmantha** [comment]
Yes. That would be useful. Since even if it is a thin mesh, it is still a mesh. And if you would like to put a tolerance around how thin a mesh you support, it could be something that can be configured.

**Comment by akuukka** [comment]
Agreed, I will update the code this week. Output will be a tetrahedron even if the point cloud forms just a line in 3D space.

**Comment by shekarmantha** [comment]
Cool. Thanjs

**Comment by akuukka** [comment]
Fixed the problem. The output is now always a proper triangle mesh, even if it has no volume.

**Comment by shekarmantha** [comment]
Thank you.
