### ISSUE TITLE
getConvexHull() doesn't always return the most optimal hull

### ISSUE THREAD

**Issue by markus-wa** [akuukka/quickhull#11]
The following test fails because the first hull wrongfully contains `(933.8125, 653.875, 0.0)`.
When the resulting vertices are run through `getConvexHull()` a second time the correct hull is created.

```cpp
TEST(QuickHull, FirstHullShouldBeOptimal) {
	QuickHull<float> qh;
	std::vector<Vector3<float>> pointCloud;
	pointCloud.emplace_back(933.8125f, 653.875f, 0.0f);
	pointCloud.emplace_back(887.8125f, 651.875f, 0.0f);
	pointCloud.emplace_back(830.8125f, 661.875f, 0.0f);
	pointCloud.emplace_back(919.8125f, 613.875f, 0.0f);
	pointCloud.emplace_back(784.8125f, 648.875f, 0.0f);
	pointCloud.emplace_back(879.8125f, 583.875f, 0.0f);
	pointCloud.emplace_back(914.8125f, 553.875f, 0.0f);
	pointCloud.emplace_back(823.8125f, 577.875f, 0.0f);
	pointCloud.emplace_back(792.8125f, 703.875f, 0.0f);
	pointCloud.emplace_back(941.8125f, 563.875f, 0.0f);
	pointCloud.emplace_back(975.8125f, 538.875f, 0.0f);
	pointCloud.emplace_back(874.8125f, 530.875f, 0.0f);
	pointCloud.emplace_back(915.8125f, 716.875f, 0.0f);
	pointCloud.emplace_back(898.8125f, 781.875f, 0.0f);
	pointCloud.emplace_back(831.8125f, 624.875f, 0.0f);
	pointCloud.emplace_back(867.8125f, 753.875f, 0.0f);
	auto first = qh.getConvexHull(pointCloud, true, false);
	auto firstVertices = first.getVertexBuffer();
	//quickhull::tests::run();

	std::vector<Vector3<float>> secondCloud;
	for each (auto var in firstVertices)
	{
		secondCloud.push_back(var);
	}

	auto second = qh.getConvexHull(secondCloud, true, false);
	EXPECT_EQ(second.getVertexBuffer().size(), firstVertices.size());
}
```

**Comment by markus-wa** [comment]
~~I just noticed `useOriginalIndices = true` fixes the issue. Is this expected/intended?~~
No of course with useOriginalIndices they will be the same as the input 😅 - that's why the test succeeds.

**Comment by akuukka** [comment]
I'm afraid it's not realistic to expect to always get optimal hulls in terms of number of vertices (ensuring that would probably make the algorithm much slower).

Both hulls in your example have the same volume and both are optimal in terms of volume (or actually area in this case since all those points on lie on the z=0 plane). They even have same number of triangles.

**Comment by markus-wa** [comment]
Thanks for the quick response.

Hmm that's unfortunate.

Until now my library returned a counter-clockwise sorted list of points for a 2D convex hull which was easy to use for drawing. If I understand correctly I'll need to adjust the API to return triangles (which is already done for 3D hulls) so the consumer will need to adjust their drawing code from drawing a single polygon to a series of triangles. (I previously used another library that could only do 2D hulls but now I would like to also have 3D hulls working).

Is my assumption correct?

**Comment by akuukka** [comment]
Yes, that's correct. You can use the index buffers returned by quickhull to draw the triangles.

**Comment by markus-wa** [comment]
Perfect, thanks a lot!
