### ISSUE TITLE
Choose an open source license

### ISSUE THREAD

**Issue by NateAM** [akuukka/quickhull#13]
Can you select a specific open source license for this code (MIT / BSD / etc ) since you have indicated that it is public domain? That would make it easier for people to contribute to its development.

Here are links to the licenses:
https://choosealicense.com/licenses/mit/
https://choosealicense.com/licenses/bsd-2-clause/

**Comment by akuukka** [comment]
I like MIT license, but how does it make it easier to contribute than public domain?

**Comment by NateAM** [comment]
The issue is that, as a developer associated with an institution, using public domain code is tricky because there isn’t a globally accepted standard of what that means. My institution may not approve the inclusion of public domain code. Having a license lets them know the legal footing they are on, and would make the inclusion trivial.

So my understanding is that without that license, I won’t be able to use the code but with it I will.

**Comment by NateAM** [comment]
@akuukka Any thoughts on whether you would be willing to make that change?

**Comment by akuukka** [comment]
Sqlite for instance is public domain and is widely used, so I find it hard to believe to that being public domain is a big problem.

Any opinions, anyone, on MIT vs. public domain?

**Comment by NateAM** [comment]
For what it's worth, I did some asking in the meantime and public domain
code is fine for my institution to incorporate. I won't say you shouldn't
do the license ( only since that makes everything obvious ) but, for my
purposes, it doesn't matter as much as I thought.
