### ISSUE TITLE
Referencing address of first element in vector instead of using data()

### ISSUE THREAD

**Issue by Pindrought** [akuukka/quickhull#20]
https://github.com/akuukka/quickhull/blob/master/Structs/VertexDataSource.hpp#L18

Using the following is problematic here since in the case of an empty vector this will cause an exception to be hit in debug mode.
```cpp
 m_ptr(&vec[0])
```

Suggested fix:
```cpp
 m_ptr(vec.data())
```

**Comment by akuukka** [comment]
Thanks! Fixed.
