### ISSUE TITLE
How to include it into a C++ project generated using visual studio 2015?

### ISSUE THREAD

**Issue by pnt1614** [akuukka/quickhull#5]
I am using the visual studio 2015 professional and I create an empty project to use your code. But there are two error messages when I build the project:

1. LNK2019	unresolved external symbol "public: class quickhull::ConvexHull<float> __thiscall quickhull::QuickHull<float>::getConvexHull(class std::vector<class quickhull::Vector3<float>,class std::allocator<class quickhull::Vector3<float> > > const &,bool,bool,float)" (?getConvexHull@?$QuickHull@M@quickhull@@QAE?AV?$ConvexHull@M@2@ABV?$vector@V?$Vector3@M@quickhull@@V?$allocator@V?$Vector3@M@quickhull@@@std@@@std@@_N1M@Z) 
2. LNK2001	unresolved external symbol "private: static float const quickhull::QuickHull<float>::Epsilon" (?Epsilon@?$QuickHull@M@quickhull@@0MB)...".

Could you tell me how to use your code in a C++ project in visual studio 2015? 

Thank you.

**Comment by akuukka** [comment]
I think you're not including QuickHull.cpp in the project. You are just #Including QuickHull.hpp from some other file (main.cpp or something created by Visual Studio for you perhaps?)

**Comment by wilsonsun** [comment]
I have the same issue, I put quickhull folder in my project additional include path and #include quickhull.hpp in the file that I want to use quickhull. It's giving me the same linking error that pnt1614 had. Any idea what the issue is?
