### ISSUE TITLE
incorrect result?

### ISSUE THREAD

**Issue by d-hoke** [akuukka/quickhull#6]
[code.zip](https://github.com/akuukka/quickhull/files/2273985/code.zip)
Not sure I've figured out exactly how results should be used, but it appears the resultant vertex buffer contains an item that should not be part of the convex hull (2d data, z's are 0)
when which = 2, 3 are used and depending on whether it includes points on another line or not should maybe not be present on which = 1 either.
![convexhulldata](https://user-images.githubusercontent.com/25270092/43896539-28e67ce2-9ba7-11e8-9a61-2fca701ff59c.png)

**Comment by d-hoke** [comment]
code is to be placed in 'tests', with that as current directory in msys2 prompt I compiled using g++ from prompt with
g++ -I.. extractbug.cpp ../QuickHull.cpp
and run as one of 
./a.exe 0
./a.exe 1
./a.exe 2
./a.exe 3
./a.exe 4
or similar to (args are processed as x,y pairs, z is zero'd)
 ./a.exe -3 4 -2 3 -3 1 1 -2 2 1 -10 0 0 -10 10 0 0 10

**Comment by d-hoke** [comment]
Someone suggested the indices might be used with the vertices to produce a triangulation, and exploring that further I can see that could be the case.  But only two triangles are needed to cover the full convexhull polygon and the index list indicates least six triangles - not sure what, if any, effect the 2D data is having on whatever is being returned.

**Comment by akuukka** [comment]
Yes, that's the case here. This quickhull algorithm is intended mainly for 3D use and can indeed produce suboptimal triangle counts in the special case where all points lie on a plane.

Fixing this would probably require using a totally different mechanism in the planar special case.
