### ISSUE TITLE
Status of Structs/Pool.hpp and Structs/VertexDataSource.hpp

### ISSUE THREAD

**Issue by starseeker** [akuukka/quickhull#7]
Hi!  I'm looking at making use of QuickHull, and while working with the code noticed two files have copyright statements:

Structs/Pool.hpp
Structs/VertexDataSource.hpp

The toplevel README.md file lists the QuickHull license as public domain, but these two files have:

Copyright © 2016 Antti Kuukka. All rights reserved.

Should they be treated differently from the rest of QuickHull, or are they covered under the public domain grant?

Thanks for publishing a nifty piece of work!
CY

**Comment by akuukka** [comment]
Oh, those copyright statements were automatically created by Xcode. I will remove them today, the Quickhull project is public domain.
