### ISSUE TITLE
Visual Studio 2013 issues

### ISSUE THREAD

**Issue by starseeker** [akuukka/quickhull#8]
I'm not sure if Visual Studio building is within scope, but I thought I'd mention two things I encountered:

1.  Need to include <cstdint> for uint_8

2.  Seeing an error relating to unique_ptr:

error C2280: 'std::unique_ptr<std::vector<quickhull::IndexType,std::allocator<_Ty>>,std::default_delete<std::vector<_Ty,std::allocator<_Ty>>>> &std::unique_ptr<std::vector<_Ty,std::allocator<_Ty>>,std::default_delete<std::vector<_Ty,std::allocator<_Ty>>>>::operator =(const std::unique_ptr<std::vector<_Ty,std::allocator<_Ty>>,std::default_delete<std::vector<_Ty,std::allocator<_Ty>>>> &)' : attempting to reference a deleted function

)' : attempting to reference a deleted function
3>          with
3>          [
3>              _Ty=quickhull::IndexType
3>          ]
3>          memory(1487) : see declaration of 'std::unique_ptr<std::vector<quickhull::IndexType,std::allocator<_Ty>>,std::default_delete<std::vector<_Ty,std::allocator<_Ty>>>>::operator ='
3>          with
3>          [
3>              _Ty=quickhull::IndexType
3>          ]
3>          This diagnostic occurred in the compiler generated function 'quickhull::MeshBuilder<FloatType>::Face &quickhull::MeshBuilder<FloatType>::Face::operator =(const quickhull::MeshBuilder<FloatType>::Face &)'
3>          with
3>          [
3>              FloatType=float
3>          ]

**Comment by starseeker** [comment]
whoops - the include for uint_8 is cstdint

**Comment by akuukka** [comment]
Thanks. It would be nice if QuickHull could be compiled using MSVC out of the box. Any chance you could make a pull request that fixes the problems?

**Comment by starseeker** [comment]
I can prepare the cstdint patch, but for the latter issue the only thing we found that worked was switching to shared_ptr instead of unique_ptr - our best guess is that there is some implicit working of a copy operator for the Face structure, which on MSVC runs afoul of the unique_ptr in the class definition of Face.

Would a patch to switch to shared_ptr be of interest?  I know it would be marginally slower - our tests with the Standford lucy model indicated about a 2x performance overhead, but since that jumped the timing from 3 to 6 seconds for our application that's acceptable...

**Comment by starseeker** [comment]
Closing issue, per #9
